### ISSUE TITLE
Unable to run Batch files

### ISSUE THREAD

**Issue by calvintomaneng** [mplutka/tm-bt-led#11]
[EDIT]
Hi Markus,

I hope all is well.

I like your work, and it's very amazing. Everything is working perfectly! Thank you so much. Take care!

Sincerely,
Calvin

**Comment by isopix** [comment]
.BAT files are MS-DOS batch files (interpreted by COMMAND.COM).

"Modern" (Windows NT era, over two decades) equalivent is .CMD files,
interpreted by CMD.EXE.

You should be safe to mass rename all .bat files to .cmd.

.bat files are limited to 8+3 file name limit and longer pathes must
be shortened.

Naming batch files .bat (instead of .cmd) is imposing other
limitations and asking problems. If software is not intended to be
MS-DOS, Windows 3.x or Windows 95/98/ME compatible, then it's not
smart move and should be fixed (I understand nostalgy for MS-DOS, but
it's a bad way showing apprecation to it)
